name: Check Pull-Request

on:
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - name: prepare Repository
      uses: actions/checkout@v2

    - name: use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Application
      run: npm install

    - name: Run Integration Tests
      run: npm run test